from utils.helpers import CustomException, logging

logging.info("Test utilities module loaded successfully.")
logging.error("This is an error message.")